### ISSUE TITLE
License? 

### ISSUE THREAD

**Issue by reiz** [zantolov/ZantolovAppBundle#1]
Under which license is this code published? MIT?

**Comment by zoka123** [comment]
Hi, code is free to use however you want to, free of charge :)

Unfortunately I didn't provided docs and really will try to put some getting started tutorial

**Comment by reiz** [comment]
OK. I send you 2 pull requests. I guess MIT is the right license for you ;-)

**Comment by zoka123** [comment]
Thank you very much! :)
